# Generated by Django 4.2.11 on 2024-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_flower_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
