# Generated by Django 4.2.11 on 2024-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_flower_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="flowers/"),
        ),
    ]
